server:
  tomcat:
    uri-encoding: utf-8
  port: 8081




spring:

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/shopping?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver


#  redis:
#    host: 127.0.0.1
#    password: huayu
#    port: 6379

#  activemq:
#    broker-url: tcp://127.0.0.1:61616
#    user: admin
#    password: admin

#  jms:
#    pub-sub-domain: false #false 代表队列

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
